# https://circleci.com/docs/2.0/language-go/
# https://circleci.com/docs/2.0/circleci-images/
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
        environment:
          DB_NAME: circle_test
          DB_PASSWORD: circle_test
      - image: circleci/postgres:10-postgis-ram
        environment:
          POSTGRES_PASSWORD: circle_test

    working_directory: /go/src/github.com/myzie/flamedb
    steps:
      - checkout
      - run: whoami
      - run: sudo apt-get install postgresql-client-10
      - run: go get -v -t -d ./...
      - run: go test -v ./...
