# https://circleci.com/docs/2.0/language-go/
# https://circleci.com/docs/2.0/circleci-images/
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
        environment:
          DB_NAME: circle_test
          DB_PASSWORD: circle_test
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:10-postgis-ram
        environment:
          POSTGRES_USER: circle_test
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test

    working_directory: /go/src/github.com/myzie/flamedb
    steps:
      - checkout
      - run: whoami
      - run: sudo apt-get install postgresql-client-9.6
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: psql -U circle_test -d $TEST_DATABASE_URL -c "CREATE TABLE test (name char(25));"
      - run: go get -v -t -d ./...
      - run: go test -v ./...
