// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateRecordHandlerFunc turns a function with the right signature into a create record handler
type CreateRecordHandlerFunc func(CreateRecordParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRecordHandlerFunc) Handle(params CreateRecordParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateRecordHandler interface for that can handle valid create record params
type CreateRecordHandler interface {
	Handle(CreateRecordParams, interface{}) middleware.Responder
}

// NewCreateRecord creates a new http.Handler for the create record operation
func NewCreateRecord(ctx *middleware.Context, handler CreateRecordHandler) *CreateRecord {
	return &CreateRecord{Context: ctx, Handler: handler}
}

/*CreateRecord swagger:route POST /records records createRecord

Create a new record

*/
type CreateRecord struct {
	Context *middleware.Context
	Handler CreateRecordHandler
}

func (o *CreateRecord) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateRecordParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
