// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateRecordOKCode is the HTTP code returned for type CreateRecordOK
const CreateRecordOKCode int = 200

/*CreateRecordOK Successfully created

swagger:response createRecordOK
*/
type CreateRecordOK struct {
}

// NewCreateRecordOK creates CreateRecordOK with default headers values
func NewCreateRecordOK() *CreateRecordOK {

	return &CreateRecordOK{}
}

// WriteResponse to the client
func (o *CreateRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CreateRecordBadRequestCode is the HTTP code returned for type CreateRecordBadRequest
const CreateRecordBadRequestCode int = 400

/*CreateRecordBadRequest Validation exception

swagger:response createRecordBadRequest
*/
type CreateRecordBadRequest struct {
}

// NewCreateRecordBadRequest creates CreateRecordBadRequest with default headers values
func NewCreateRecordBadRequest() *CreateRecordBadRequest {

	return &CreateRecordBadRequest{}
}

// WriteResponse to the client
func (o *CreateRecordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
