// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteRecordHandlerFunc turns a function with the right signature into a delete record handler
type DeleteRecordHandlerFunc func(DeleteRecordParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRecordHandlerFunc) Handle(params DeleteRecordParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteRecordHandler interface for that can handle valid delete record params
type DeleteRecordHandler interface {
	Handle(DeleteRecordParams, interface{}) middleware.Responder
}

// NewDeleteRecord creates a new http.Handler for the delete record operation
func NewDeleteRecord(ctx *middleware.Context, handler DeleteRecordHandler) *DeleteRecord {
	return &DeleteRecord{Context: ctx, Handler: handler}
}

/*DeleteRecord swagger:route DELETE /records/{recordId} records deleteRecord

Deletes a record

*/
type DeleteRecord struct {
	Context *middleware.Context
	Handler DeleteRecordHandler
}

func (o *DeleteRecord) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRecordParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
