// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRecordNotFoundCode is the HTTP code returned for type DeleteRecordNotFound
const DeleteRecordNotFoundCode int = 404

/*DeleteRecordNotFound Record not found

swagger:response deleteRecordNotFound
*/
type DeleteRecordNotFound struct {
}

// NewDeleteRecordNotFound creates DeleteRecordNotFound with default headers values
func NewDeleteRecordNotFound() *DeleteRecordNotFound {

	return &DeleteRecordNotFound{}
}

// WriteResponse to the client
func (o *DeleteRecordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
