// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/myzie/flamedb/models"
)

// NewUpdateRecordParams creates a new UpdateRecordParams object
// no default values defined in spec.
func NewUpdateRecordParams() UpdateRecordParams {

	return UpdateRecordParams{}
}

// UpdateRecordParams contains all the bound params for the update record operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateRecord
type UpdateRecordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Override user ID
	  In: header
	*/
	XUserID *string
	/*Record to be updated
	  Required: true
	  In: body
	*/
	Record *models.RecordInput
	/*ID of record to be updated
	  Required: true
	  In: path
	*/
	RecordID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateRecordParams() beforehand.
func (o *UpdateRecordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXUserID(r.Header[http.CanonicalHeaderKey("X-User-ID")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RecordInput
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("record", "body"))
			} else {
				res = append(res, errors.NewParseError("record", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Record = &body
			}
		}
	} else {
		res = append(res, errors.Required("record", "body"))
	}
	rRecordID, rhkRecordID, _ := route.Params.GetOK("recordId")
	if err := o.bindRecordID(rRecordID, rhkRecordID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateRecordParams) bindXUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XUserID = &raw

	return nil
}

func (o *UpdateRecordParams) bindRecordID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RecordID = raw

	return nil
}
