// Code generated by go-swagger; DO NOT EDIT.

package records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/myzie/flamedb/models"
)

// UpdateRecordOKCode is the HTTP code returned for type UpdateRecordOK
const UpdateRecordOKCode int = 200

/*UpdateRecordOK Successfully updated

swagger:response updateRecordOK
*/
type UpdateRecordOK struct {

	/*
	  In: Body
	*/
	Payload *models.RecordOutput `json:"body,omitempty"`
}

// NewUpdateRecordOK creates UpdateRecordOK with default headers values
func NewUpdateRecordOK() *UpdateRecordOK {

	return &UpdateRecordOK{}
}

// WithPayload adds the payload to the update record o k response
func (o *UpdateRecordOK) WithPayload(payload *models.RecordOutput) *UpdateRecordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update record o k response
func (o *UpdateRecordOK) SetPayload(payload *models.RecordOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateRecordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateRecordBadRequestCode is the HTTP code returned for type UpdateRecordBadRequest
const UpdateRecordBadRequestCode int = 400

/*UpdateRecordBadRequest Validation exception

swagger:response updateRecordBadRequest
*/
type UpdateRecordBadRequest struct {
}

// NewUpdateRecordBadRequest creates UpdateRecordBadRequest with default headers values
func NewUpdateRecordBadRequest() *UpdateRecordBadRequest {

	return &UpdateRecordBadRequest{}
}

// WriteResponse to the client
func (o *UpdateRecordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateRecordNotFoundCode is the HTTP code returned for type UpdateRecordNotFound
const UpdateRecordNotFoundCode int = 404

/*UpdateRecordNotFound Record not found

swagger:response updateRecordNotFound
*/
type UpdateRecordNotFound struct {
}

// NewUpdateRecordNotFound creates UpdateRecordNotFound with default headers values
func NewUpdateRecordNotFound() *UpdateRecordNotFound {

	return &UpdateRecordNotFound{}
}

// WriteResponse to the client
func (o *UpdateRecordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
